In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\mekal\Downloads\dirty_cafe_sales.csv")
df.isnull().sum()
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [2]:
df.replace(['ERROR','UNKNOWN'],np.nan,inplace=True)
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [4]:
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'],errors='coerce')
df['Total Spent']=pd.to_numeric(df['Total Spent'],errors='coerce')
df['Transaction Date']=pd.to_datetime(df['Transaction Date'],errors='coerce')

In [5]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [6]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [7]:
df['Item'].fillna(df['Item'].mode()[0], inplace=True)

C:\Users\mekal\AppData\Local\Temp\ipykernel_280\303095028.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Item'].fillna(df['Item'].mode()[0], inplace=True)

In [8]:
df['Quantity'].fillna(df['Quantity'].median(),inplace=True)

C:\Users\mekal\AppData\Local\Temp\ipykernel_280\549334851.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].median(),inplace=True)

In [9]:
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [10]:
df['Price Per Unit'].fillna(df['Price Per Unit'].mean(),inplace=True)

C:\Users\mekal\AppData\Local\Temp\ipykernel_280\3702569498.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price Per Unit'].fillna(df['Price Per Unit'].mean(),inplace=True)

In [11]:
df['Total Spent'].fillna(df['Total Spent'].mean(),inplace=True)

C:\Users\mekal\AppData\Local\Temp\ipykernel_280\1098853838.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total Spent'].fillna(df['Total Spent'].mean(),inplace=True)

In [12]:
df['Payment Method'].fillna('Unknown',inplace=True)
df['Location'].fillna('Unknown',inplace=True)
df['Transaction Date'].fillna(df['Transaction Date'].mode()[0],inplace=True)

C:\Users\mekal\AppData\Local\Temp\ipykernel_280\1768900818.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment Method'].fillna('Unknown',inplace=True)
C:\Users\mekal\AppData\Local\Temp\ipykernel_280\1768900818.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Location'].fillna('Unknown',inplace=True)
C:\Users\mekal\AppData\Local\Temp\ipykernel_280\1768900818.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Transaction Date'].fillna(df['Transaction Date'].mode()[0],inplace=True)

In [13]:
df['Total Spent']=df['Quantity']*df['Price Per Unit']

In [14]:
df['Calculated Total']=df['Quantity']*df['Price Per Unit']

In [15]:
df['Day'] = df['Transaction Date'].dt.day_name()

In [16]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Calculated Total    0
Day                 0
dtype: int64

In [17]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total,Day
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,Friday
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,Tuesday
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,Wednesday
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,Unknown,2023-04-27,10.0,Thursday
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,Sunday
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,Unknown,2023-03-31,20.0,Friday
6,TXN_4433211,Juice,3.0,3.0,9.0,Unknown,Takeaway,2023-10-06,9.0,Friday
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,Unknown,2023-10-28,16.0,Saturday
8,TXN_4717867,Juice,5.0,3.0,15.0,Unknown,Takeaway,2023-07-28,15.0,Friday
9,TXN_2064365,Sandwich,5.0,4.0,20.0,Unknown,In-store,2023-12-31,20.0,Sunday
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,25.0,Tuesday
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,2023-02-06,8.0,Monday
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03,8.0,Wednesday
13,TXN_9437049,Cookie,5.0,1.0,5.0,Unknown,Takeaway,2023-06-01,5.0,Thursday
14,TXN_8915701,Juice,2.0,1.5,3.0,Unknown,In-store,2023-03-21,3.0,Tuesday
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15,15.0,Wednesday
16,TXN_3765707,Sandwich,1.0,4.0,4.0,Unknown,Unknown,2023-06-10,4.0,Saturday
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24,6.0,Friday
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,Unknown,2023-03-25,15.0,Saturday
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15,12.0,Sunday

In [18]:
df.to_csv("cleaned_data.csv", index=False)

In [19]:
df.info()
df.isnull().sum()
df.head()
df.describe()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  datetime64[ns]
 8   Calculated Total  10000 non-null  float64
 9   Day               10000 non-null  object
dtypes: datetime64[ns](1), float64(4), object(5)
memory usage: 781.4+ KB

np.int64(0)

In [20]:
df.describe()

,Quantity,Price Per Unit,Total Spent,Transaction Date,Calculated Total
count,10000.000000,10000.000000,10000.000000,10000,10000.000000
mean,3.027100,2.949984,8.939857,2023-06-25 05:52:13.440000,8.939857
min,1.000000,1.000000,1.000000,2023-01-01 00:00:00,1.000000
25%,2.000000,2.000000,4.000000,2023-03-19 00:00:00,4.000000
50%,3.000000,3.000000,8.000000,2023-06-24 00:00:00,8.000000
75%,4.000000,4.000000,12.000000,2023-09-27 00:00:00,12.000000
max,5.000000,5.000000,25.000000,2023-12-31 00:00:00,25.000000
std,1.384614,1.243910,5.828088,NaN,5.828088

5

8

11

8

even

power of 2